### ISSUE TITLE
Not able to add multiple children to a child

### ISSUE THREAD

**Issue by caden-at-pieces** [EllisMin/file-structure-generator#9]
See how I cannot add another children to a child of the main directory.

https://github.com/EllisMin/file-structure-generator/assets/171293373/85428369-30fe-43b9-93c2-c6389f319eac

**Comment by EllisMin** [comment]
@caden-at-pieces
Hi there, in your example, it looks like you might be wanting to add a direct child to `child-1` or "test1". If so, it can be done by clicking on the down arrow button on the right side of "test1". Sorry about the UI, I know it can be confusing

**Comment by caden-at-pieces** [comment]
Ohh that makes a lot more sense, thank you!
